ghstack/submit.py

Make the summary message properly display the top of stack

---

ghstack/__main__.py
ghstack/config.py
ghstack/diff.py
ghstack/git.py
ghstack/github_real.py
ghstack/land.py
ghstack/submit.py
ghstack/unlink.py
test_ghstack.py

This is required for enterprise github deployments

Custom github urls / look in parent directories for config

---

ghstack/config.py

Now this is how it looks like
```
(py37_base) alexander.sidorov@C02Z96HPLVDL ~/Dev/test (test2) $ ghstack
GitHub url [github.com]: github.example.com
GitHub OAuth token (make one at https://github.example.com/settings/tokens -- we need public_repo permissions):
GitHub username: salex
NB: configuration saved to ~/.ghstackrc
```
Test plan:
1. run on public repo,  it generated config under home directory
2. moved config under a subfolder where I store public repos
3. run on enterprise repo, config was generated under home directory as expected
4. now running on either of the repos does not prompt and uses correct credentials

Fix config creation process for custom git URLs

---

setup.py

Sorry for being trivial, but this fixes #26

Update url for homepage

---

ghstack/github_utils.py

fix missing comma

---

ghstack/config.py

Not sure why I didn't catch this in b07b6a139ccf2c40b919047ff430b1dc09f260f0.

Change remaining logging.warn to logging.warning

---

ghstack/land.py

Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#46 Improve ghstack land to "merge" and delete branches.**
I realized there is a simple trick for convincing GitHub that a PR
has been merged, rather than closed: merge the head branch into the
base branch!  We can't (easily) induce this when we do an actual master
merge commit, because there isn't actually any relationship between the
master commit and the pull request (which is a request to merge head
into base--master is completely unrelated).
Also, because people really seem to hate it when ghstack leaves tons
of branches lying around, I also updated the logic to delete the
branches at merge time (this doesn't lose data, because GitHub keeps
track of the pull request branch at time of merge itself).  One
slightly goofy thing …

Improve ghstack land to "merge" and delete branches.

---

ghstack/submit.py
test_ghstack.py

Closes #23.
Let's say we have a stack with two commits (listed here in reverse chronological order):
- `gh/user/Y`
- `gh/user/X`
Let's say that `origin/gh/user/Y/base` is out of date, and we run `ghstack` to update these on GitHub.
- Currently, `origin/gh/user/Y/base` is an ancestor of (local) `gh/user/X/head`, then we update `origin/gh/user/Y/base` to be `gh/user/X/head`. Otherwise, we update `origin/gh/user/Y/base` to be a merge commit whose parents are:
- (the previous) `origin/gh/user/Y/base`
- (the new) `gh/user/X/head`
- After this PR, regardless of any ancestral relationship, if `origin/gh/user/Y/base` is not equal to `gh/user/X/head`, we update `origin/gh/user/Y/base` to be a new commit whose _only parent_ is (the previous) `origin/gh/user/Y/base`.
This reduces the number of cases …

Don't unexpectedly merge when commits are reordered

---

ghstack/submit.py
test_ghstack.py

Stack from [ghstack](https://github.com/ezyang/ghstack):
* __->__ #83
* #79

Strip mentions from commit messages to avoid spam

---

ghstack/submit.py

As a follow-up to #92, this allows moving checks that we
currently run on git's `pre-push` hook to be run at a `pre-ghstack`
time instead by configuring a git hook named `pre-ghstack`.
When running the submit action, if this hook is found, run it,
passing the base and head commit ids as arguments (to help
the hook to determine the changes that are being submitted),
and only proceed if successful.
For reference, our intended implementation of this hook is to run:
`pre-commit run --hook-stage push --from-ref "$1" --to-ref "$2"`

Add support for `pre-ghstack` git hook

---

ghstack/diff.py
ghstack/git.py
ghstack/shell.py
ghstack/submit.py
test_ghstack.py

Preserve authorship when running ghstack for the first time

---

ghstack/github_utils.py
test_ghstack.py

Like #111 but also for https urls

support dots in https urls too

---

.flake8
ghstack/github.py
ghstack/github_fake.py
ghstack/github_real.py
ghstack/land.py

Land: If force pushes allowed on protected branch, use that.

---

ghstack/github.py
ghstack/github_fake.py
ghstack/land.py
test_ghstack.py

Land: Don't attempt to land already closed PRs

---

ghstack/submit.py

Fix company name (NFC)

---

ghstack/__init__.py
mypy.ini
poetry.lock
pyproject.toml

update required importlib_metadata versions

---

.github/workflows/test.yml
poetry.lock
pyproject.toml

add black@^22.12.0 to pyproject.toml; set 3.8 as minimum Python version

---

emitter.py
ghstack/__main__.py
ghstack/action.py
ghstack/cache.py
ghstack/checkout.py
ghstack/circleci.py
ghstack/circleci_real.py
ghstack/config.py
ghstack/diff.py
ghstack/forensics.py
ghstack/git.py
ghstack/github.py
ghstack/github_fake.py
ghstack/github_real.py
ghstack/github_utils.py
ghstack/gpg_sign.py
ghstack/land.py
ghstack/logs.py
ghstack/rage.py
ghstack/shell.py
ghstack/status.py
ghstack/submit.py
ghstack/types.py
ghstack/unlink.py
run_tests.sh
test_ghstack.py
test_shell.py

autoformat project: `poetry run black .`

---

ghstack/github_fake.py
poetry.lock
pyproject.toml

remove dataclasses from pyproject.toml

---

.github/workflows/test.yml

https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages

Install poetry following setup-python caching examples

---

.github/workflows/test.yml
README.md
run_tests.py
run_tests.sh

Tests should also be run on the Windows OS. As this is OSS, the increase in the required capacity might not have the biggest impact.

ci: test also on `windows-latest`

---

test_ghstack.py

In #176, I described an error which occurs during tests on Windows. The error occurs when trying to delete files after executing tests. The error occurs because of missing permissions (likely the files to delete are read-only).
I fixed this deletion issue by checking if the file/dir to delete cannot be written. If this is the case, I modify the permission and retry the deletion.
The tests which had the described issue in the class `TestGh` now pass. The other test failures left on Windows are different and still existent.

fix: modify file permissions when deletion fails in tests

---

ghstack/shell.py
ghstack/submit.py

Disable password prompt by default on HTTPS, better error message

---

ghstack/submit.py
test_ghstack.py

* __->__ #181
Fixes https://github.com/ezyang/ghstack/issues/170

Better error message when landed PR has had branch removed

---

ghstack/submit.py
test_ghstack.py

* __->__ #182
Fixes https://github.com/ezyang/ghstack/issues/143

Explicitly specify refspec when doing fetch

---

ghstack/checkout.py
ghstack/cli.py
ghstack/config.py
ghstack/github.py
ghstack/github_real.py
ghstack/submit.py

* __->__ #185
Fixes https://github.com/ezyang/ghstack/issues/134

Make GitHub token optional; make checkout work without it

---

ghstack/submit.py
test_ghstack.py

Don't strip @ from email addresses

---

ghstack/land.py
test_ghstack.py

* #190
* __->__ #189
* #188
Fixes https://github.com/ezyang/ghstack/issues/133

Refuse to land a closed PR

---

ghstack/submit.py
test_ghstack.py

* __->__ #190
* #189
* #188
Fixes https://github.com/ezyang/ghstack/issues/121

Refuse to handle stacks that are too large, without --force

---

ghstack/submit.py
test_ghstack.py

* __->__ #191
Fixes https://github.com/ezyang/ghstack/issues/108

Improve guidance when trying to reland closed PR

---

ghstack/cli.py
ghstack/submit.py
test_ghstack.py

* #193
* __->__ #192
Fixes https://github.com/ezyang/ghstack/issues/82

Add --base/-B flag to ghstack, for non-standard base

---

ghstack/submit.py
test_ghstack.py

* __->__ #193
Fixes https://github.com/ezyang/ghstack/issues/74

Insert divider when PR body has bullet list at top

---

ghstack/config.py

* __->__ #195
* #194
Fixes https://github.com/ezyang/ghstack/issues/184

Make GitHub url prompt less error prone

---

ghstack/submit.py
test_ghstack.py

* #207
* #206
* #205
* #202
* #204
* __->__ #203
* #200

Refactor structure of ghstack.submit

---

ghstack/cli.py
ghstack/submit.py
test_ghstack.py

* #207
* #206
* #205
* #202
* __->__ #204
* #203
* #200

Add detailed invariants checking that is toggled for test suite

---

ghstack/submit.py

* #207
* #206
* __->__ #205
* #202
* #204
* #203
* #200

Repair hook support, sort of buggily

---

ghstack/cli.py

* #207
* __->__ #206
* #205
* #202
* #204
* #203
* #200

Fix default --stack value

---

ghstack/land.py

* __->__ #207
Fixes https://github.com/ezyang/ghstack/issues/63

Keep going if branch deletion fails

---

test_ghstack.py

Test for issue #62

---

ghstack/submit.py
test_ghstack.py

Reorganize ghstack/submit.py quite a bit

---

ghstack/submit.py

* #213
* #212
* #211
* __->__ #210

Merge prepare_submit and prepare_rebase together

---

ghstack/submit.py

* #213
* #212
* __->__ #211
* #210

Rename commit to diff where it represents Diff

---

ghstack/submit.py

* #213
* __->__ #212
* #211
* #210

Start working on next, fix a bug

---

ghstack/submit.py

* __->__ #213
* #212
* #211
* #210

Refactor PushBranches

---

ghstack/submit.py

* #219
* #218
* #217
* #216
* #215
* __->__ #214

Don't prefix base with remote name

---

ghstack/submit.py

* #219
* #218
* #217
* #216
* __->__ #215
* #214

Create elab_diff after creating PR

---

ghstack/submit.py

* #219
* #218
* #217
* __->__ #216
* #215
* #214

Some preliminary support for direct merges, it's not all working yet

---

ghstack/submit.py

* #219
* #218
* __->__ #217
* #216
* #215
* #214

Refactor DiffMeta to have less fields

---

ghstack/diff.py
ghstack/submit.py

* #219
* __->__ #218
* #217
* #216
* #215
* #214

Store github_url on PullRequestResolved

---

ghstack/submit.py

* __->__ #219
* #218
* #217
* #216
* #215
* #214

Unconditionally populate information on GhBranches, even if no update

---

ghstack/cli.py
ghstack/submit.py
test_ghstack.py

Some initial support for direct, still incomplete

---

ghstack/submit.py
test_ghstack.py

* #224
* #223
* #222
* __->__ #221

Increase direct testing, fix redundant base bug

---

test_ghstack.py

* #224
* #223
* __->__ #222
* #221

Simplify some tests

---

ghstack/submit.py
test_ghstack.py

Setup base branch changes

---

ghstack/github_fake.py
ghstack/submit.py
test_ghstack.py

Put the stack navigation in a separate GitHub comment

---

ghstack/submit.py
test/land/default_branch_change.py.test
test/land/invalid_resubmit.py.test
test/land/update_after_land.py.test
test/submit/amend.py.test
test/submit/amend_all.py.test
test/submit/amend_bottom.py.test
test/submit/amend_message_only.py.test
test/submit/amend_top.py.test
test/submit/bullet_divider.py.test
test/submit/cherry_pick.py.test
test/submit/commit_amended_to_empty.py.test
test/submit/do_not_revert_local_commit_msg_on_skip.py.test
test/submit/empty_commit.py.test
test/submit/multi.py.test
test/submit/no_clobber.py.test
test/submit/no_clobber_carriage_returns.py.test
test/submit/non_standard_base.py.test
test/submit/rebase.py.test
test/submit/reject_head_stack.py.test
test/submit/remove_bottom_commit.py.test
test/submit/reorder.py.test
test/submit/simple.py.test
test/submit/strip_mentions.py.test
test/submit/unrelated_malformed_gh_branch_ok.py.test
test/submit/update_fields.py.test
test/submit/update_fields_preserve_differential_revision.py.test
test/submit/update_fields_preserves_commit_message.py.test
test/unlink/basic.py.test

Fixes https://github.com/ezyang/ghstack/issues/61

Don't include PR title inside head/base commits

---

ghstack/cli.py
ghstack/submit.py
ghstack/test_prelude.py

Prepare for direct inference by renaming the flag in cli

---

pyproject.toml

Hi again! Is this the right way to make the changes since https://github.com/ezyang/ghstack/commit/0c412bf0d9515e11b58cddaeb1b1d9f0b17a5295 accessible?
:) Thanks so much

Release 0.9.4

---

README.md

slightly reword README

---

src/ghstack/github_real.py
src/ghstack/submit.py
test/submit/throttle.py.test

Fixes: #267
Original PR: https://github.com/ezyang/ghstack/pull/289 credit @bdaz

Respect GitHub ratelimit to support more than 8 stacked PRs

---

src/ghstack/github_real.py

More help text for repository moved case

---

src/ghstack/github_utils.py

Signed-off-by: Edward Yang <ezyang@meta.com>

Add some extra docs for repo not found case
