ezyang/ghstack

ghstack/submit.py
Whoops, `reversed()` is not an in-place operation.
=> actually fix the stack summary

ghstack/__main__.py, ghstack/submit.py
This PR adds a `--draft` command-line option that, if passed, creates PRs in draft mode. This means that reviewers will not be notified and the PR cannot be merged without marking it as "ready for review."
=> Add --draft option to create PR in draft mode

ghstack/__main__.py, ghstack/checkout.py, ghstack/config.py, ghstack/land.py, ghstack/submit.py, ghstack/unlink.py, test_ghstack.py
I like to use "upstream" for the main repo and point "origin" to my fork.
=> Make remote name configurable instead of assuming origin

ghstack/__main__.py, ghstack/config.py, ghstack/github_real.py, ghstack/land.py, ghstack/submit.py, ghstack/unlink.py, test_ghstack.py
At my company, the master branch is `dev`, so ghstack doesn't work great out of the box. To make it work for me, I made the master branch's name a config option!
How I tested this:
* I added `default_branch = dev` to my `~/.ghstackrc`
* Rebased my stack of commits on `dev`
* Ran `ghstack` and it worked!
=> Make default branch name configurable

ghstack/github_utils.py
https://github.com/ezyang/ghstack/pull/13 added custom GitHub URL. But the change didn't wasn't applied to checkout.
I relaxed the PR URL regex a bit. I could also pass down the custom URL from the `github` object [here](https://github.com/ezyang/ghstack/blob/master/ghstack/checkout.py#L17) if you think that's a better approach.
=> relax checkout PR url regex

emitter.py, poetry.lock, pyproject.toml, run_tests.sh
[(example)](https://github.com/samestep/ghstack/runs/1864748746)
This has a few advantages:
- since `pytest` intercepts the output of passing tests, the CI log is less noisy
- this runs the doctests automatically (since we already set `addopts = --doctest-modules` in `pytest.ini`)
- this shows deprecation warnings that weren't very visible previously
I had to wrap part of `emitter.py` in `if __name__ == '__main__'` because it was breaking when  `pytest` tried to look in it for tests to collect.
=> Run tests using pytest

detailed-mypy.ini, run_tests.sh, test_expecttest.py, test_ghstack.py, test_shell.py
This PR makes the linting/typechecking more declarative and thus easier to integrate with editors like VS Code that run Flake8 and `mypy` on individual files (so we avoid [this situation](https://github.com/pytorch/pytorch/pull/50826)); for instance, this `.vscode/settings.json` now works:
```json
{
"python.venvPath": "~/Library/Caches/pypoetry/virtualenvs",
"python.pythonPath": "~/Library/Caches/pypoetry/virtualenvs/ghstack-RjXx9-bl-py3.6/bin/python",
"python.linting.enabled": true,
"python.linting.flake8Enabled": true,
"python.linting.mypyEnabled": true,
"python.linting.mypyArgs": [
"--config-file=detailed-mypy.ini"
]
}
```
I also enabled `show_error_codes` to make it easier to add scoped `# type: ignore` comments (such as the one added to `test_shell.py` in this PR).
=> Don't constrain Flake8 and mypy to specific files

ghstack/config.py, ghstack/submit.py, ghstack/unlink.py, test_ghstack.py
Resolves #35.
This PR doesn't remove all instances of `master` from the codebase; rather, it just fixes a couple minor issues:
- The `main` functions in `ghstack.submit` and `ghstack.unlink` previously specified default values for some of their arguments that duplicated the default values already defined in `ghstack.config`, so now they require values to always be passed for those arguments.
- As mentioned in the issue thread, GitHub now names the default branch `main` for new repos, so `ghstack` would previously just fail when used on such a repo. Now it asks the user for the default branch if it's not already set in the config, similar to what it does for `github_url`.
=> Don't hardcode master as much

ghstack/shell.py, test_shell.py
This PR makes `ghstack` always print logged commands in a form that can be copied and pasted directly into a shell. For example, previously `ghstack` would print commands like this:
```
$ git for-each-ref refs/remotes/origin/gh/samestep --format=%(refname)
```
Running the above in `zsh` gives this error message:
```
zsh: missing end of string
```
With this PR, `ghstack` instead prints this, which works properly:
```
$ git for-each-ref refs/remotes/origin/gh/samestep '--format=%(refname)'
```
As shown in this example, only the args that actually need quoting are quoted, so no unnecessary noise is added.
One possible downside is that now `log_command` prints any newlines as literal newlines (albeit in quotes), e.g. in `test_shell.py`. However, this seems better than the previous behavior, …
=> Quote logged shell command args where necessary

ghstack/__main__.py
It looks like this was added to `ghstack.__main__` in bdba14b2f1d43db4a01d8e9d2452c501eb8950b3 and then later to `ghstack.config` in 60238391e2527ce05426f8519da73cd1a8508c3b, but while the latter commit removed the redundant `GITHUB_OAUTH` `redact` from `ghstack.__main__`, it didn't remove the corresponding `CIRCLE_TOKEN` redact; hence this PR.
=> Remove redundant CircleCI token redact

ghstack/__main__.py, ghstack/config.py, ghstack/github_fake.py, ghstack/github_utils.py, ghstack/land.py, ghstack/submit.py, ghstack/unlink.py, test_ghstack.py
Followup to [this discussion in #39](https://github.com/ezyang/ghstack/pull/39#discussion_r575613008). This PR does the following:
This PR does not cache the default branch because I'm not sure how to properly do that if a repository's default branch can change over time.
=> Fetch default branch from GitHub API

.github/workflows/test.yml
Example: https://github.com/ezyang/ghstack/pull/46/commits/a9a2b09e6f715e64dd10f504baa2a9f764375d1b
A more elegant solution might be (instead of restricting the `push` trigger) to somehow modify the `pull_request` trigger to only run on PRs from forks, but this solution should also work fine.
=> Don't run double GitHub Actions on PRs

ghstack/github_fake.py
Currently, VS Code fails to [discover the tests](https://code.visualstudio.com/docs/python/testing#_enable-a-test-framework) (at least on macOS), because I think for some reason the locale is being set to ASCII, so `pytest` fails when reading the GitHub GraphQL schema:
https://github.com/ezyang/ghstack/blob/ecc3c401ab4b78e99ba7441897fe70c22b050ed5/ghstack/github_fake.py#L240-L242
This PR specifies the encoding explicitly, so now VS Code can successfully be used to run the tests (and debug specific ones, thanks to #53):
```json
{
"python.testing.pytestArgs": [
"."
],
"python.testing.unittestEnabled": false,
"python.testing.nosetestsEnabled": false,
"python.testing.pytestEnabled": true
}
```
=> Set encoding when reading github_schema.graphql

ghstack/submit.py, test_ghstack.py
Fixes #52, repairing the two tests (`test_rebase` and `test_cherry_pick`) that #44 kind of broke.
=> Allow rebases again by merging in the stack base

ghstack/config.py
I was getting this error previously:
```
ghstack/config.py:155: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/sestep/.ghstackrc' mode='w' encoding='UTF-8'>
config.write(open(config_path, 'w'))
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
=> Autoclose config file after writing

ghstack/submit.py, test_ghstack.py
there could be malformed ghstack branch names manually created.
this change removed those non-numeric, malformed ghstack when checking max ref num
=> dealt with malformed ghstack branch name

ghstack/submit.py, test_ghstack.py
#69 dealt with the recent GitHub UI change by removing the duplicate bolded PR title from `ghstack`-generated PR descriptions, with the hope that simply bolding the PR number would be enough. However, this unfortunately does not work; see https://github.com/pytorch/pytorch/pull/60204 for an example:
This PR replaces the ineffective attempt at bolding with a bolded arrow to the left of the PR title and number:
=> Use a bold arrow to indicate the current PR

ghstack/gpg_sign.py, ghstack/submit.py, ghstack/unlink.py, test_ghstack.py
This PR implements GPG signing behavior in ghstack.
This implementation mimics the behavior of git.
This PR resolves https://github.com/ezyang/ghstack/issues/77
=> implement GPG signing behavior

ghstack/checkout.py, ghstack/land.py, ghstack/submit.py
Stack from [ghstack](https://github.com/ezyang/ghstack):
* #83
* __->__ #79
Pruning is not enabled by default for git because it is technically
destructive, but in practice noone really cares if we stomp all over
remote refs, especially because there are always tons and tons of
changes to remote refs in a ghstack workflow.
In return, we never have a situation where fetch fails because someone
did something naughty to a remote ref that git refuses to update, e.g.,
and error like:
```
error: cannot lock ref 'refs/remotes/origin/opinfo/one_hot': 'refs/remotes/origin/opinfo' exists; cannot create 'refs/remotes/origin/opinfo/one_hot'
! [new branch]            opinfo/one_hot          -> origin/opinfo/one_hot  (unable to update local ref)
```
=> Unconditionally prune on fetches

chrome-extension/ghstack.js, chrome-extension/manifest.json
Stack from [ghstack](https://github.com/ezyang/ghstack):
* **#60 Add simple Chrome extension to delete merge button on ghstack PRs**
It's wrong to click these buttons, so this PR makes it marginally
safer.
=> Add simple Chrome extension to delete merge button on ghstack PRs

ghstack/submit.py
As I found out today, it's not obvious to reviewers which way the PR stack goes. I had a reviewer prioritize the topmost PRs thinking that they were the oldest.
=> Clarify ordering of PR stack

ghstack/shell.py
This allows git hooks to detect execution inside `ghstack`. Our use case is that we have some pre-push checks that, when run inside `ghstack`, frequently fails due to the large number of pushes, so we want to tweak its behavior when these hooks are run inside `ghstack`.
=> Add environment variable GHSTACK=1 on git executions

ghstack/submit.py
It only exists on `github.com` but not other github URLs
=> Fix link to ghstack

poetry.lock, pyproject.toml
Currently, `[tool.poetry.dependencies]` is configured to only allow `typing-extensions` with major version `3`. `typing-extensions` was bumped to version `4`; I believe the only significant change is dropping Python 3.5 support, which is already unsupported by other dependencies. Allow version 4 to be used to avoid unnecessary package conflicts when installed in existing virtualenvs.
=> Allow `typing-extensions` version `4.x`

poetry.lock
`poetry update pytest` to get https://github.com/pytest-dev/pytest/pull/8540 for Python 3.10 compatibility
=> Bump pytest 6.2.2 -> 6.2.5

ghstack/github_utils.py, test_ghstack.py
The regular expression didn't account for that. `.+?` is a non-greedy match, so that the next expression will still pick up the `.git` at the end.
=> GitHub repositories can have dots in the name

ghstack/github_utils.py, test_ghstack.py
Summary:
I had cloned a repo and ended up with a remote uri like `https://github.com/evangrayk/foo.git`. `ghstack` was not parsing this correctly due to the trailing `.git`, due to #113.
The fix is to add a check to the regex for a trailing `.git`.
Test Plan:
Added test cases, tests pass
=> Fix https remote urls with trailing .git

ghstack/diff.py, ghstack/submit.py
* __->__ #117
* #116
This is convenient for our internal integration.
=> Allow author_name and author_email to be None

ghstack/cache.py
=> assert is a keyword, not a function

ghstack/submit.py
Was getting this locally, Ed suggested patching it out, but in case others hit it, I figure we can safely skip with a message.
=> Skip pre ghstack hook if git fails to run

poetry.lock, pyproject.toml, run_tests.sh
mypy 0.800 depends on `typed-ast==1.4.3` which is not compatible with
arm64/M1 Macs, resulting in being unable to install/test ghstack on
those machines.
=> Upgrade mypy for arm64/M1 Mac compatibility

test_ghstack.py
Fixes issues with tests getting stuck waiting for user input.
=> Add --no-edit to git commits in tests

.gitignore, run_tests.sh
- Adds pyenv version marker and common virtualenv name to .gitignore
- Updates `run_tests` script to specifically link ghstack dir/module
This improves the ability to build and test this project when using a
virtualenv, so that dependencies aren't installed to shared/global
site-packages.
=> Improve virtualenv developer experience

poetry.lock, pyproject.toml
Resolves the open security alert related to having the `py` package in
the dependency tree (a transitive dep of pytest 6). This upgrades
pytest, drops `py` from deps, and should resolve the security alert.
https://github.com/ezyang/ghstack/security/dependabot/5
=> Upgrade to pytest 7

.github/workflows/test.yml, README.md
* #147
* #146
* #145
* __->__ #144
Peotry lockfile requires Python 3.8+, but readme still mentions 3.6.
Updates readme accordingly, and also adds CI to validate 3.10 and 3.11,
along with equivalent jobs for macOS.
=> Update supported versions

.github/workflows/test.yml
* #147
* #146
* __->__ #145
* #144
This upgrades the version of poetry installed in CI from 1.1.7 to 1.3.2.
The new version supports the new lockfile format, and fixes a number of
runtime bugs that currently present on arm64/M1 Macs.
Updating the lockfile format happens in the next diff in the stack.
=> Upgrade poetry version used in CI

.github/workflows/test.yml, README.md, run_tests.py, run_tests.sh
I am ashamed that I ignored the problem of running .sh scripts on Windows. :see_no_evil: 
Instead of maintaining a separate Bash and Powershell script, I transformed the script into a simple Python script. After a rebase, #167 should also succeed.
Currently, I cannot really test on a Windows machine. However, in Powershell and standard Ubuntu containers, the execution works smoothly.
=> chore: transform test script into Python

.github/workflows/test.yml
I first tried to rabbit hole into specifying many sub-dependencies. However, this results in very old dependencies and a complicated list of dependencies. As it eventually turned out, I just needed to update the Poetry version which gets installed during our CI process.
Testing the project with a recent version of Poetry fixes the experienced dependency issues and closes #172.
=> ci: install Poetry version `1.7.1`

README.md
A while back, Python 3.12 became ga. We should therefore also test with this new Python version. As `ghstack` is OSS, the increase in the required capacity might not have the biggest impact.
=> docs: do not run tests on Python 3.12

ghstack/diff.py, ghstack/git.py, ghstack/submit.py
* #200
* #199
* __->__ #198
I am trying to implement incremental updates and the patch abstraction
is the wrong way to go about doing it, because you in general don't have
a base tree to apply the patch on; you need the full git tree object
somehow.  This will break ghexport when we take these updates but it's
going to be complicated to handle anyway, deal with it when we get
there.
=> Undo Patch abstraction

ghstack/git.py, ghstack/submit.py, ghstack/unlink.py
=> Make CommitHeader use cached_property

ghstack/cli.py, ghstack/diff.py, ghstack/git.py, ghstack/shell.py, ghstack/submit.py, test_ghstack.py
* #207
* #206
* #205
* #202
* #204
* #203
* __->__ #200
Fixes https://github.com/ezyang/ghstack/issues/123
Fixes https://github.com/ezyang/ghstack/issues/101
=> Rewrite ghstack head/base commit construction algorithm

ghstack/submit.py, test_ghstack.py
* #207
* #206
* #205
* __->__ #202
* #204
* #203
* #200
=> Invariant testing for GitHub global state and HEAD state

.github/workflows/test.yml, README.md
With our recent version upgrades, tests also succeed with Python 3.12. By adding testing with Python 3.12, we can ensure that ghstack works with all current Python versions.
=> ci: test with Python 3.12

ghstack/config.py, ghstack/github_real.py
references:
- GraphQL API: https://docs.github.com/en/enterprise-server@3.12/graphql/guides/forming-calls-with-graphql#the-graphql-endpoint
- REST API: https://docs.github.com/en/enterprise-server@3.12/rest/meta/meta?apiVersion=2022-11-28#github-api-root
=> Fix github enterprise api url

ghstack/config.py, ghstack/github_real.py
Fix for https://github.com/ezyang/ghstack/pull/235.
Add `res.raise_for_status()` so that request failures result in a better exception (instead of failing to parse the response json).
=> fix: Fix handling of github url

ghstack/config.py
Request `repo` instead of `public_repo` scope token to allow `ghstack` to be used in private repositories.
Fixes #234
=> feat: Request token at `repo` scope

ghstack/submit.py, test/land/default_branch_change.py.test, test/land/invalid_resubmit.py.test, test/land/update_after_land.py.test, test/submit/amend.py.test, test/submit/amend_all.py.test, test/submit/amend_bottom.py.test, test/submit/amend_message_only.py.test, test/submit/amend_top.py.test, test/submit/bullet_divider.py.test, test/submit/cherry_pick.py.test, test/submit/commit_amended_to_empty.py.test, test/submit/do_not_revert_local_commit_msg_on_skip.py.test, test/submit/empty_commit.py.test, test/submit/multi.py.test, test/submit/no_clobber.py.test, test/submit/no_clobber_carriage_returns.py.test, test/submit/non_standard_base.py.test, test/submit/rebase.py.test, test/submit/reject_head_stack.py.test, test/submit/remove_bottom_commit.py.test, test/submit/reorder.py.test, test/submit/simple.py.test, test/submit/unrelated_malformed_gh_branch_ok.py.test, test/submit/update_fields.py.test, test/submit/update_fields_preserve_differential_revision.py.test, test/submit/update_fields_preserves_commit_message.py.test, test/unlink/basic.py.test
* __->__ #241
Fixes https://github.com/ezyang/ghstack/issues/238
=> Add a parent commit pointing to orig base to help CI scripts out

ghstack/submit.py, test/land/update_after_land.py.test, test/submit/amend_all.py.test, test/submit/amend_bottom.py.test, test/submit/amend_top.py.test, test/submit/empty_commit.py.test, test/submit/multi.py.test, test/submit/no_clobber_carriage_returns.py.test, test/submit/reorder.py.test, test/submit/simple.py.test, test/submit/unrelated_malformed_gh_branch_ok.py.test, test/unlink/basic.py.test
=> Hotfix: properly prefix base with remote name

ghstack/submit.py
=> Check .github/ghstack_direct to decide if using direct by default

ghstack/config.py
For https://github.com/ezyang/ghstack/issues/260
Read user config file path from `$GHSTACKRC_PATH` if it's set, with `~/.ghstackrc` as default fallback
=> Read ghstackrc from `$GHSTACKRC_PATH` before falling back to `~/.ghstackrc`

README.md, ghstack/github_utils.py, ghstack/land.py
Allows for 
```
ghstack land 1234
```
instead of 
```
ghstack land https://github.com/origin/repo/pull/1234
```
I guess we could do the same with checkout and such - LMK if I should do a single PR or a PR stack with these!
=> Parse PR number directly

README.md, ghstack/checkout.py, ghstack/github_utils.py, ghstack/land.py, test/github_utils/get_repo_name_with_owner.py.test
Same as #263 but for `ghstack checkout`
=> checkout PR number

src/ghstack/submit.py
I ran into an issue reordering diffs in a direct stack (the one currently ending in https://github.com/pytorch/executorch/pull/9586) where GitHub's API complained `There are no new commits between base branch 'gh/swolchok/395/head' and head branch 'gh/swolchok/383/head'`. This seems to have fixed it for me.
=> RFC: Push diffs in Git before telling GitHub about it

src/ghstack/submit.py
If 
1. you have pre-commit hooks
2. As part of your rebase you break pre-commit hooks (which don't run on rebases!). Or alternately you locally do a commit with `--no-verify`
3. You run `ghstack`
Then, `ghstack` fails with an error like
```
$ git commit-tree -p c4f05f3f02d4523f99ba0fd5b6a80eef03ea3be2 ccf059a081a7f086252c77ae3edfeee8845a2246
$ git commit-tree -p 54f88cde23b09c8e9d0c15cea04677deba04d37c e858f7a23e46b586a511222661ed8f3902da344a
$ git push origin 54f88cde23b09c8e9d0c15cea04677deba04d37c:refs/heads/gh/chillee/58/base 51d6f0469e788e120698546861ff9178eaebcee3:refs/heads/gh/chillee/58/head
error: failed to push some refs to 'github.com:iterationlab/monorepo.git'
$ git remote get-url --push origin
ERROR: Fatal exception
Traceback (most recent call last):
File …
```
=> Add `--no-verify` to ghstack submission

src/ghstack/land.py
I think after the merge the head branch is supposed(?) to be deleted, so git bails out on the whole command, not deleting any branches.
In principle I think we can just avoid deleting the head ref altogether but Chesterton's fence and all that.
=> Update land.py to delete head ref separately from orig ref and base ref

src/ghstack/diff.py, src/ghstack/land.py, src/ghstack/submit.py, test/land/default_branch_change.py.test, test/land/ff.py.test, test/land/ff_stack.py.test, test/land/ff_stack_two_phase.py.test, test/land/invalid_resubmit.py.test, test/land/non_ff.py.test, test/land/non_ff_stack_two_phase.py.test, test/land/update_after_land.py.test, test/submit/do_not_revert_local_commit_msg_on_skip.py.test, test/submit/strip_mentions.py.test
pytorch/pytorch has also been updated to support this new trailer: https://github.com/pytorch/pytorch/pull/153528
=> Updated land.py to do merging after push was successful

README.md
The name of the example workflow has changed.
Also suggests a small readability change
=> Fix pointer to sample workflow for landing ghstacks

src/ghstack/submit.py
We have an issue in https://github.com/pytorch/pytorch/issues/154427#issuecomment-2940623897 where people reportedly used an older version of ghstack which made a new PR on the same commit.  An easy way to debug this issue in the future is to mention the ghstack version that is used to create the stack in the PR description itself.
I add the version into the URL to make it less intrusive.
https://github.com/pytorch/pytorch/pull/155179#issue-3119502241
=> Print ghstack version in PR description
